# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('day_create', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('day_create', models.DateField(blank=True, null=True)),
                ('text', models.CharField(max_length=500, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docx.Event')),
            ],
            options={
                'verbose_name': 'Служебная записка',
                'verbose_name_plural': 'Служебные записки',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('day_create', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
        migrations.CreateModel(
            name='PeopleToWhom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Адресат',
                'verbose_name_plural': 'Адресаты',
            },
        ),
        migrations.AddField(
            model_name='memo',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docx.Note'),
        ),
        migrations.AddField(
            model_name='memo',
            name='to_whom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docx.PeopleToWhom'),
        ),
    ]
