# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('day_create', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'События',
                'verbose_name': 'Событие',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('day_create', models.DateField(blank=True, null=True)),
                ('text', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Служебные записки',
                'verbose_name': 'Служебная записка',
            },
        ),
        migrations.CreateModel(
            name='MemoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('day_create', models.DateField()),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docx.Memo')),
            ],
            options={
                'verbose_name_plural': 'Заметки',
                'verbose_name': 'Заметка',
            },
        ),
        migrations.CreateModel(
            name='PeopleToWhom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Адресаты',
                'verbose_name': 'Адресат',
            },
        ),
        migrations.CreateModel(
            name='PeopleWho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=100)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('second_name', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_mobile_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Исполнители',
                'verbose_name': 'Исполнитель',
            },
        ),
        migrations.AddField(
            model_name='memo',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docx.MemoStatus'),
        ),
        migrations.AddField(
            model_name='memo',
            name='to_whom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docx.PeopleToWhom'),
        ),
        migrations.AddField(
            model_name='memo',
            name='who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docx.PeopleWho'),
        ),
        migrations.AddField(
            model_name='event',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docx.Memo'),
        ),
    ]
