# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docx', '0002_auto_20170917_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_end',
            field=models.BooleanField(default=False),
        ),
    ]
