# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docx', '0002_auto_20170824_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docx.Event'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docx.Note'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docx.PeopleWho'),
        ),
    ]
