# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-17 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docx', '0003_note_note_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplewho',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
