# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docx', '0004_auto_20170824_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='day_create',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='day_create',
            field=models.DateField(),
        ),
    ]
