# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docx', '0005_auto_20170824_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peoplewho',
            old_name='name',
            new_name='family',
        ),
        migrations.AddField(
            model_name='peoplewho',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='peoplewho',
            name='phone_mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peoplewho',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peoplewho',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peoplewho',
            name='second_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
