# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('dept', '0001_initial'), ('dept', '0002_auto_20161216_2242'), ('dept', '0003_auto_20161216_2245'), ('dept', '0004_auto_20161216_2252'), ('dept', '0005_auto_20161216_2258'), ('dept', '0006_auto_20161216_2316'), ('dept', '0007_auto_20161216_2319'), ('dept', '0008_auto_20161216_2331'), ('dept', '0009_auto_20161216_2348'), ('dept', '0010_auto_20161217_0007'), ('dept', '0011_auto_20161217_0009'), ('dept', '0012_holiday_typ')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField(blank=True, null=True)),
                ('fileurl', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('startday', models.DateField()),
                ('lenght', models.IntegerField()),
                ('stopday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=30)),
                ('secondname', models.CharField(blank=True, max_length=30, null=True)),
                ('birtday', models.DateField(blank=True, null=True)),
                ('dayofwork', models.DateField(blank=True, null=True)),
                ('telefon', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('function', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dept.Function')),
            ],
        ),
        migrations.AddField(
            model_name='holiday',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.People'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='holiday',
            name='typ',
            field=models.CharField(choices=[('план', 'план'), ('факт', 'факт')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
