# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('fileurl', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateTimeField()),
                ('startday', models.DateField()),
                ('lenght', models.IntegerField()),
                ('stopday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=30)),
                ('secondname', models.CharField(max_length=30)),
                ('birtday', models.DateField()),
                ('dayofwork', models.DateField()),
                ('telefon', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('function', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dept.Function')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.Holiday')),
            ],
        ),
    ]
