# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0002_people_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'verbose_name': 'Описание смены', 'verbose_name_plural': 'Описание смен'},
        ),
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'verbose_name': 'Отпуск', 'verbose_name_plural': 'Отпуска'},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'Персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'График работы', 'verbose_name_plural': 'Графики работы'},
        ),
        migrations.AlterModelOptions(
            name='weekend',
            options={'verbose_name': 'Отгулы и выходные', 'verbose_name_plural': 'Отгулы и выходные'},
        ),
        migrations.AddField(
            model_name='change',
            name='numer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
