# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0002_auto_20161217_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('struct', models.CharField(max_length=31)),
                ('startday', models.DateField()),
                ('starttime', models.TimeField()),
                ('stoptime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Weekend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motive', models.CharField(choices=[('Служеб.', 'Служебное задание'), ('Семейн.', 'Семейные обстоятельства'), ('Другое ', 'Другое')], default=2, max_length=8)),
                ('datestart', models.DateField()),
                ('timestart', models.TimeField()),
                ('stoptime', models.TimeField()),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.People')),
            ],
        ),
    ]
