# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0003_auto_20161216_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='birtday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='dayofwork',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='holiday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dept.Holiday'),
        ),
        migrations.AlterField(
            model_name='people',
            name='telefon',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
