# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0003_schedule_weekend'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekend',
            name='typ',
            field=models.CharField(choices=[('выходной', 'выходной'), ('отгул', 'отгул'), ('без содержания', 'без содержания')], default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weekend',
            name='motive',
            field=models.CharField(choices=[('Служеб.', 'Служебное задание'), ('Семейн.', 'Семейные обстоятельства'), ('Другое ', 'Другое')], max_length=8),
        ),
    ]
