# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0003_auto_20161221_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='numer',
            new_name='number',
        ),
    ]
