# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0004_auto_20161217_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('starttime', models.TimeField()),
                ('stoptime', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='weekend',
            name='typ',
            field=models.CharField(choices=[('Выходной', 'Выходной'), ('Отгул', 'Отгул'), ('Без содержания', 'Без содержания')], max_length=16),
        ),
    ]
