# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0004_auto_20161221_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='lenght',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='stopday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
