# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0005_auto_20161216_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='function',
        ),
        migrations.AddField(
            model_name='people',
            name='function',
            field=models.ManyToManyField(to='dept.Function'),
        ),
    ]
