# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0005_auto_20161217_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='change',
            old_name='tittle',
            new_name='title',
        ),
    ]
