# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0006_auto_20161216_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='function',
        ),
        migrations.AddField(
            model_name='people',
            name='function',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dept.Function'),
            preserve_default=False,
        ),
    ]
