# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0007_auto_20161216_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='holiday',
        ),
        migrations.AddField(
            model_name='holiday',
            name='people',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='dept.People'),
            preserve_default=False,
        ),
    ]
