# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0008_auto_20161216_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='fileurl',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='function',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
