# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0009_auto_20161216_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='year',
            field=models.IntegerField(),
        ),
    ]
