# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0011_auto_20161217_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='typ',
            field=models.CharField(choices=[('план', 'план'), ('факт', 'факт')], default=1, max_length=4),
            preserve_default=False,
        ),
    ]
