# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('si8device', '0002_auto_20170112_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.TextField()),
                ('working', models.TextField(blank=True, null=True)),
                ('working_ok', models.BooleanField(default=False)),
                ('time_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_ok', models.DateTimeField(default=django.utils.timezone.now)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si8device.Equipment')),
            ],
            options={
                'verbose_name': 'Журнал передачи смен',
                'verbose_name_plural': 'Журнал передачи смен',
            },
        ),
    ]
