# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0002_auto_20171002_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmemo',
            name='time_ok',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='time_ok',
        ),
        migrations.AddField(
            model_name='historicalmemo',
            name='time_repair',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='time_repair',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
