# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament_name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'si8_departament',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_enable', models.BooleanField()),
                ('equipment_name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'si8_equipment',
            },
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollresult_value', models.FloatField()),
                ('pollresult_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'si8_pollresult',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_enable', models.BooleanField()),
                ('register_name', models.CharField(max_length=200)),
                ('register_addr', models.IntegerField()),
                ('register_regname', models.CharField(max_length=60)),
                ('register_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si8device.Equipment')),
            ],
            options={
                'db_table': 'si8_register',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(max_length=60)),
                ('sector_departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si8device.Departament')),
            ],
            options={
                'db_table': 'si8_sector',
            },
        ),
        migrations.AddField(
            model_name='pollresult',
            name='pollresult_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si8device.Register'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='si8device.Sector'),
        ),
    ]
