# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('si8device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': 'Цех', 'verbose_name_plural': 'Цех'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelOptions(
            name='pollresult',
            options={'verbose_name': 'Результат опроса', 'verbose_name_plural': 'Результат опроса'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Устройство', 'verbose_name_plural': 'Устройство'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Участок', 'verbose_name_plural': 'Участок'},
        ),
        migrations.AlterField(
            model_name='pollresult',
            name='pollresult_time',
            field=models.CharField(max_length=60),
        ),
    ]
