# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('si8parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файлы', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Папки', 'verbose_name_plural': 'Папки'},
        ),
    ]
